name: devnet-bundle-release-action
description: Devnet Bundle Release Action

inputs:
  nexus_id:
    description: "Nexus ID"
    required: true
  nexus_user:
    description: "Nexus User"
    required: true
  nexus_user_pw:
    description: "Nexus User Password"
    required: true
  nexus_url:
    description: "Nexus Url"
    required: true
  nexus_url_release:
    description: "Nexus Url Release"
    required: true
  nexus_url_snapshots:
    description: "Nexus Url Snapshots"
    required: true
  release_token:
    description: "Release Token"
    required: true
  git_mail:
    description: "Release Version"
    required: true
  git_user:
    description: "Next Dev Version"
    required: true
  release_version:
    description: "Release Version"
    required: true
  next_dev_version:
    description: "Next Dev Version"
    required: true

runs:
  using: "composite"
  steps:
    - id: checkout
      uses: actions/checkout@v2
    - id: setup
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - id: git
      name: Set GIT username and email
      run: |
        git config --global user.email "${{ git_mail }}"
        git config --global user.name "${{ git_user }}"
    - id: create_settings_xml
      name: "Create settings.xml"
      uses: whelk-io/maven-settings-xml-action@v18
      with:
        repositories: >
          [
            {
              "id": "central",
              "url": "http://central",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "true"
              }
            }
          ]
        plugin_repositories: >
          [
            {
              "id": "central",
              "url": "http://central",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "true"
              }
            }
          ]
        servers: >
          [
            {
              "id": "${{ nexus_id }}",
              "username": "${{ nexus_user }}",
              "password": "${{ nexus_user_pw }}"
            }
          ]
        mirrors: >
          [
            {
              "id": "${{ nexus_id }}",
              "mirrorOf": "central",
              "url": "${{ nexus_url }}"
            }
          ]
    - id: cache-node
      name: Cache node modules
      uses: actions/cache@v2
      with:
        path: |
          '**/node'
          '**/node_modules'
          ~/.m2/repository
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package.json') }}
    - id: write_release_versions
      name: Update versions to ${{ release_version }}
      run: |
        mvn validate -P write-release-versions -Dreplace.target.version=${{ release_version }}
        mvn versions:set -DnewVersion=${{ release_version }} -DgenerateBackupPoms=false
        mvn scm:checkin -DpushChanges=true -Dmessage="[update-version] to ${{ release_version }}" -Dscm.username=${{ git_user }} -Dscm.password=${{ release_token }}
    - id: tests
      name: Run tests
      run: mvn prepare-package -Prun-js-tests,include-mapapps-deps
    - id: nexus_deployment
      name: Publish to Nexus
      run: mvn deploy -Pcompress -Dmaven.test.skip.exec=true -Ddist.releases.id=${{ nexus_id }} -Ddist.releases.url=${{ nexus_url_release }} -Ddist.snapshots.id=${{ nexus_id }} -Ddist.snapshots.url=${{ nexus_url_snapshots }}
    - id: project_artifact_id
      name: Extract Maven project artifactId
      run: echo ::set-output name=artifactId::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec)
    - id: release
      name: Create GitHub release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "target/${{ steps.project_artifact_id.outputs.artifactId }}-bundle.zip,target/${{ steps.project_artifact_id.outputs.artifactId }}-sample-app.zip"
        preRelease: false
        bodyFile: "RELEASE.md"
        allowUpdates: true
        replacesArtifacts: true
        tag: ${{ release_version }}
        token: ${{ release_token }}
    - id: write_dev_versions
      name: Update versions to ${{ next_dev_version }}
      run: |
        mvn validate -P write-release-versions -Dreplace.target.version=${{ next_dev_version }}
        mvn versions:set -DnewVersion=${{ next_dev_version }} -DgenerateBackupPoms=false
        mvn scm:checkin -DpushChanges=true -Dmessage="[update-version] to ${{ next_dev_version }}" -Dscm.username=${{ git_user }} -Dscm.password=${{ release_token }}
